### ISSUE TITLE
Hibernate

### ISSUE THREAD

**Issue by thomashunziker** [quantumdb/quantumdb#34]
This project looks very interesting. Have you ever tried to used it in combination with Hibernate or another JPA provider?

**Comment by michaeldejong** [comment]
Hi @thomashunziker . Yes we did some tests with Hibernate about a year ago which seemed to work well at the time. All you would need to do is include the `quantumdb-driver` into your project, and slightly alter the database connection string: `jdbc:quantumdb:postgresql://localhost:5432/<your-database>?version=<schema-version>`. I've also tried it with JOOQ, which also seemed to work without issue.

We started writing [some online documentation](http://quantumdb.io/docs/0.2/), but it's only a start. The project itself is still much in the alpha/beta phase, and not production-ready. If you do end up giving it a try and have some feedback. Let us know!

**Comment by thomashunziker** [comment]
Dear Micheal,
Thank you for your respond. We use in our production environment currently an approach by which we reduce the outage to the migration time. However the approach of quantumdb is much better. We will try to introduce your solution into our application. I will keep you posted how our progress is. Eventually we will provide also some pull requested when we have some improvements. Our biggest issue is that we have to migrate also data which can be quite hard and we need to see if we can handle this in our application.
Regards,
Thomas

**Comment by michaeldejong** [comment]
I'd love to hear from you as you progress. Keep me updated! :)
