### ISSUE TITLE
"==> Unsupported type: numeric" & "==> null" errors

### ISSUE THREAD

**Issue by NGRichter** [quantumdb/quantumdb#59]
Hi, I'm currently looking at solutions for zero-downtime database schema migrations for my master thesis and this project is the only one available online.
Some other solutions that are proposed in literature are the following:
[Ratchet](https://escholarship.org/uc/item/62f8259r)
[Terrier](http://ra.adm.cs.cmu.edu/anon/home/anon/usr0/ftp/2019/CMU-CS-19-104.pdf)
[InVerDa](https://dl.acm.org/doi/abs/10.1145/3035918.3064046)
[DECA](https://www.scitepress.org/papers/2018/68451/68451.pdf)
These were never released which is a shame.

I do have some problems when running the init command.
First is the error: "==> Unsupported type: numeric" when attempting to initialize an existing database. I use the tpcc database created by HammerDB.

When I first initialized an empty database it went alright, but the changelog command set something wrong and now it always returns "==> null" whatever I do.

I have tested this with 2 PostgreSQL versions, 13.2 and 9.6.21. I run the commands on a Debian 10.8 VM.

Is this a known problem and is there a workaround?

**Comment by NGRichter** [comment]
Okay, I did some more testing.
I fixed the unsupported type: numeric by adding the type in the ColumnType and PostgresTypes files.
The '==> null' error is due to the changelog.xml file I had in the folder from where I ran the command.

**Comment by michaeldejong** [comment]
Sorry for the delay, this got buried somewhere in my notifications.

That is indeed the correct fix for the `numeric` type. Note that there are probably more types missing (and their aliases).

Thanks for the list of new solutions/papers, I see some familiar names cited, so I'll be giving these a read. Unfortunately it's quite common that these tools themselves never get published. You could ask the authors to provide a copy, but don't expect too much. I've had far better luck with "commercial" options like gh-ost, percona, osc, etc.
