### ISSUE TITLE
"Preview" / "dry-run" / "updateSQL" command

### ISSUE THREAD

**Issue by NGRichter** [quantumdb/quantumdb#65]
Before I start implementing new features I will put them here to start a discussion and exchange some ideas.

Before an update, it might be nice to have a command to see which statements get executed on the database, a sort of dry run.
I propose a command to simulate a fork without the actual execution. This would be the same as the [updateSQL](https://docsstage.liquibase.com/commands/community/updatesql.html) command of Liquibase. 

I believe most changes, if not all, will be in the TableCreator and TableDataMigrator classes where the actual tables are made and data is migrated. Some functionality needs to be made so that it can write the statements to a file or to the command line.

I believe this command is needed before organizations can adopt QuantumDB as a solution. Database administrators need to know exactly what gets executed on the database. They could go through the source code, but that would take some time before they know where to find what.

**Comment by michaeldejong** [comment]
Sounds great. It was actually mentioned at some point during the development of quantumdb but I never really went to the top of the priority list. It's probably not too hard. You'd want to intercept the writes quantumdb makes to the database and log them somewhere. The only challenge I can think of is that some parts of the migration (I'm guessing mostly the data migration part) might be tricky as they could be dependent on whatever a previous (write) query returned. But the `CREATE TABLE` and `CREATE TRIGGER`, etc. queries should probably be pretty doable. Another consideration is that table names and function names are generated randomly. So what this command produces might not be exactly what is executed.

Another option would be to print out the constructed `Plan` object into more human readable text. It doesn't produce any SQL, but it's pretty helpful for debugging. Came in useful for verifying/testing the more complex migrations.

I guess the question is: how comprehensive do you want the output to be?

**Comment by michaeldejong** [comment]
I might have an idea for this, but let me know if you had any thoughts on this (or perhaps already started). No idea on an ETA though.

**Comment by NGRichter** [comment]
I have already implemented some functionality, but I haven't tested it much. 
I will create a pull request so you can already see what I have done and provide feedback.
