### ISSUE TITLE
"Cleanup" command

### ISSUE THREAD

**Issue by NGRichter** [quantumdb/quantumdb#66]
With the cleanup (or another name) command I want to propose the functionality that will rename all tables to their original name.

If someone is using QuantumDB for a while and then decides to not use it anymore they are left with table names that do not mean anything to them. With this functionality, all table names will be renamed to their original names. The query rewriting can be stopped after this command.

Of course, this can only function if there is only 1 active version, as otherwise multiple tables need the same name. When the command has finished, 2 versions are active because clients are still connected to the "old" version. Whenever this version gets dropped QuantumDB can be removed without downtime.

I see some obstacles on edge cases such as what happens when a table that already has the correct name has to be renamed due to a table with foreign keys getting renamed but that issue is for when the functionality gets implemented.

**Comment by michaeldejong** [comment]
This one seems a little tricky, but definitely useful. A bit like `delombok` for the Lombok library. Could definitely make it easier for people to trial quantumdb on a database.

> Of course, this can only function if there is only 1 active version, as otherwise multiple tables need the same name. When the command has finished, 2 versions are active because clients are still connected to the "old" version. Whenever this version gets dropped QuantumDB can be removed without downtime.

Yes so the aim is not to perform atomic renames like the other tools do, but instead create a new fork (with no structural changes), where any table not using their real name gets a ghost table assigned with their real name. Data must be copied over and kept in sync, and like you suggested, the clients can then safely use the original postgresql JDBC driver.

> I see some obstacles on edge cases such as what happens when a table that already has the correct name has to be renamed due to a table with foreign keys getting renamed but that issue is for when the functionality gets implemented.

I think you'll be ok here. Any table with their original name still can only have FKs that point to original tables, and be referred to by either ghost tables or original tables. The former is what you're interested in. The main challenge I think will be changing the planner / migrator to not use randomly generated table names, but specific ones. As well as figuring out which tables and how they'll need to be migrated.

If you want to take a stab at it 👍 . If you have specific questions let me know.
